# Generated by Django 4.0.5 on 2022-08-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_signup',
            name='username',
            field=models.EmailField(max_length=254),
        ),
    ]
